Repository inno-24/algorithm-study, pull requests merged in 2024-09, with the labels that each got.

#52 [2024-08-29] 김채린 #36
  김채린/2109.java
  김채린/21940.java
Labels: 1팀문제

#55 [2024-08-30] 정은화 #42
  정은화/28702.js
Labels: 3팀문제

#56 [2024-08-30] 조수인#41
  조수인/1003.java
Labels: 2팀문제

#57 [2024-08-30] 김무성 #42
  김무성/28702/28702.js
  김무성/28702/input.txt
Labels: 3팀문제

#61 [2024-09-03] 박지은 #59
  박지은/2109.java
Labels: 1팀문제

#62 [2024-09-03] 박서희 #59
  박서희/2109.py
  박서희/21940.py
Labels: 1팀문제

#63 [2024-09-03] 박찬영, [BOJ] 2109번, 순회강연 #59
  박찬영/2109.js
  박찬영/input.txt
Labels: 1팀문제

#66 [2024-09-04] 박찬영 #58
  Main.java
  main.class
  박찬영/1182/Main.java
Labels: 2팀문제

#65 [2024-09-04] 정은화 #60
  정은화/2798.js
Labels: 3팀문제

#67 [2024-09-04] 김무성 #60
  김무성/2798/2798.js
  김무성/2798/input.txt
Labels: 3팀문제

#68 [2024-09-04] 류진식 #58
  류진식/1182/1182.js
  류진식/1182/input.txt
Labels: 2팀문제

#72 [2024-09-05] 박찬영 [BOJ] 12851번, 숨바꼭질 2 #64
  박찬영/12851/Main.java
  박찬영/12851/index.js
  박찬영/12851/input.txt
  박찬영/1668/input.js
  박찬영/1668/input.txt
Labels: 1팀문제

#73 [2024-09-05] 박지은 #64 BOJ 12851 숨바꼭질
  박지은/12851.java
Labels: 1팀문제

#74 [2024-09-06] 김무성 #69
  김무성/1668/1668.js
  김무성/1668/input.txt
Labels: 3팀문제

#79 2024-09-12, 박찬영 #78
  박찬영/2206/input.js
  박찬영/2206/input.txt
Labels: 1팀문제

#82 [2024-09-12] 박지은 #78 BOJ 2206 벽 부수고 이동하기
  박지은/2206.java
Labels: 1팀문제

#83 [2024-09-13] 박광열 #80
  박광열/1668.js
  박광열/17219.js
  박광열/4134.js
  박광열/input.txt
Labels: 2팀문제

#84 [2024-09-13] 김무성 #80 #81
  김무성/1259/1259.js
  김무성/1259/input.txt
  김무성/4134/4134.js
  김무성/4134/input.txt
Labels: 2팀문제, 3팀문제
