Repository inno-24/algorithm-study, pull requests merged in 2024-08, with the labels that each got.

#22 [2024-08-22] 김무성 #16
  2675/2675.js
  2675/input.txt
Labels: 3팀문제

#24 [2024-08-22] 박지은, 2096번, 내려가기
  박지은/2096.java
Labels: 1팀문제

#29 [2024-08-23] 조수인 #15
  조수인/14405.java
Labels: 2팀문제

#30 [2024-08-23] 김무성 #15
  김무성/14405/14405.js
  김무성/14405/input.txt
  김무성/2675/2675.js
  김무성/2675/input.txt
Labels: 2팀문제

#39 [2024-08-28] 박찬영, 랜선자르기
  박찬영/1654.js
  박찬영/8983.js
  박찬영/input.txt
Labels: 2팀문제

#40 [2024-08-28] 조수인 #33
  조수인/1654.java
  조수인/1654.py
Labels: 2팀문제

#43 [2024-08-28] 박광열 #33
  박광열/1654.js
Labels: 2팀문제

#44 [2024-08-28] 박지은 #33
  박지은/1654.java
Labels: 2팀문제

#45 [2024-08-28] 김무성 #32 #33
  김무성/1654/1654.js
  김무성/1654/input.txt
  김무성/8958/8958.js
  김무성/8958/input.txt
Labels: 2팀문제, 3팀문제

#46 [2024-08-28] 정은화 #32
  정은화/8958.js
Labels: 3팀문제

#47 [2024-08-27] 류진식 #33
  류진식/1654/1654.js
  류진식/1654/input.txt
Labels: 2팀문제

#48 [2024-08-28] 이승현 #15 #33
  이승현/14405.java
  이승현/1654.java
Labels: 2팀문제

#53 [2024-08-30] 박찬영, 1003번 피보나치 함수 #41
  박찬영/1003.js
  박찬영/21940.js
  박찬영/28702.js
  박찬영/input.txt
Labels: 2팀문제
